#!/usr/bin/env python3
"""lib/data/codec/cp949_table.dart 생성기.

CP949(EUC-KR 상위 호환) 2바이트 → UTF-16 매핑을 하나의 Dart 문자열 상수로 만든다.
인덱스 = (lead - 0x81) * 178 + trailIndex. 매핑 없는 칸은 U+FFFD.
trail 범위: 0x41-0x5A, 0x61-0x7A, 0x81-0xFE (총 178).
Python 표준 codecs만 사용. 실행: python3 tool/gen_cp949_table.py
"""
import codecs, pathlib

TRAILS = list(range(0x41, 0x5B)) + list(range(0x61, 0x7B)) + list(range(0x81, 0xFF))
assert len(TRAILS) == 178

cells = []
for lead in range(0x81, 0xFF):
    for trail in TRAILS:
        try:
            ch = codecs.decode(bytes([lead, trail]), 'cp949')
        except UnicodeDecodeError:
            ch = '�'
        assert len(ch) == 1
        cells.append(ch)

def esc(c):
    if c == '\\' or c == "'" or c == '$':
        return '\\' + c
    return c

rows = [''.join(esc(c) for c in cells[i:i + 178]) for i in range(0, len(cells), 178)]
out = pathlib.Path(__file__).resolve().parent.parent / 'lib/data/codec/cp949_table.dart'
out.write_text(
    '// GENERATED by tool/gen_cp949_table.py — 수정하지 마세요.\n'
    '// CP949 2바이트 → UTF-16 매핑. 한 줄 = lead 바이트 하나(0x81~0xFE), 178칸.\n'
    '// ignore_for_file: lines_longer_than_80_chars\n\n'
    'const String cp949Table =\n' +
    '\n'.join(f"    '{r}'" for r in rows) + ';\n',
    encoding='utf-8',
)
print(out, len(cells), 'cells')
